=== dotskapes/pyagents/resources/DiagDeviceRespiratoryPanel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 sp1 (http://www.altova.com) by Dan (SIMI) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="DiagDevRespiratoryPanel">
		<xs:annotation>
			<xs:documentation>root element - diagnostic device respiratory panel results</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="DateTime" type="xs:dateTime"/>
							<xs:element name="SourceID">
								<xs:simpleType>
									<xs:restriction base="xs:nonNegativeInteger">
										<xs:maxExclusive value="9"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="SampleID" type="xs:string"/>
							<xs:element name="Location" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Longitude">
											<xs:simpleType>
												<xs:restriction base="xs:decimal">
													<xs:fractionDigits value="6"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Latitude">
											<xs:simpleType>
												<xs:restriction base="xs:decimal">
													<xs:fractionDigits value="6"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Device" type="xs:string"/>
							<xs:element name="DeviceID" type="xs:string"/>
							<xs:element name="DevicePlexity">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:maxExclusive value="999"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="AssaySetID" type="xs:string"/>
							<xs:element name="LotID" type="xs:string"/>
							<xs:element name="Control" type="xs:integer"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="LineDetail" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Test" type="xs:string"/>
							<xs:element name="LOINC" type="xs:string" minOccurs="0"/>
							<xs:element name="Result">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:maxExclusive value="9"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Footer">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Technician" type="xs:string"/>
							<xs:element name="Status">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:maxExclusive value="9"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Calibration">
								<xs:simpleType>
									<xs:restriction base="xs:integer">
										<xs:maxExclusive value="9"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="Software" type="xs:string"/>
							<xs:element name="DeviceVersion" type="xs:string" minOccurs="0"/>
							<xs:element name="Diagnostics" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dotskapes/pyagents/testing/data/fiona.xml
<DiagDevRespiratoryPanel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DiagDeviceRespiratoryPanel.xsd"><Header><DateTime>2012-11-01T18:24:00</DateTime><SourceID>0</SourceID><SampleID>7883-3-030</SampleID><Device>BioFire FilmArray</Device><DeviceID>00301683</DeviceID><DevicePlexity>17</DevicePlexity><AssaySetID>Respiratory Panel IVD v1.6</AssaySetID><LotID>112912</LotID><Control>1</Control></Header><LineDetail><Test>Adenovirus</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Coronavirus 229E</Test><LOINC>41003-5</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Coronavirus HKU1</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Coronavirus NL63</Test><LOINC>41005-0</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Coronavirus OC43</Test><LOINC>41009-2</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Human Metapneumovirus</Test><LOINC>40978-9</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Human Rhinovirus/Enterovirus</Test><LOINC>unknown</LOINC><Result>1</Result></LineDetail><LineDetail><Test>Influenza A</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Influenza B</Test><LOINC>29907-3</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Parainfluenza Virus 1</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Parainfluenza Virus 2</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Parainfluenza Virus 3</Test><LOINC>unknown</LOINC><Result>1</Result></LineDetail><LineDetail><Test>Parainfluenza Virus 4</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Respiratory Syncytial Virus</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Bordetella pertussis</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Chlamydophila pneumoniae</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><LineDetail><Test>Mycoplasma pneumoniae</Test><LOINC>unknown</LOINC><Result>0</Result></LineDetail><Footer><Technician>Operator:</Technician><Status>1</Status><Calibration>0</Calibration><Software>1.3 Build 12/21/2011 2:21:18PM (80)</Software><DeviceVersion>none</DeviceVersion><Diagnostics>none</Diagnostics></Footer></DiagDevRespiratoryPanel>
